version: '3.5'

services:
  id-web:
    container_name: id_web_container
    image: gcr.io/boldbi-294612/bold-identity:6.8.9
    restart: on-failure
    environment:
      - APP_BASE_URL=<app_base_url>
      - INSTALL_OPTIONAL_LIBS=mongodb,mysql,influxdb,snowflake,oracle,clickhouse,google
    volumes: 
      - boldservices_data:/application/app_data
    networks:
      - boldservices
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  id-api:
    container_name: id_api_container
    image: gcr.io/boldbi-294612/bold-identity-api:6.8.9
    restart: on-failure
    volumes: 
      - boldservices_data:/application/app_data
    networks:
      - boldservices
    depends_on:
      - id-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  id-ums:
    container_name: id_ums_container
    image: gcr.io/boldbi-294612/bold-ums:6.8.9
    restart: on-failure
    environment:
      - BOLD_SERVICES_HOSTING_ENVIRONMENT=docker
      - BOLD_SERVICES_UNLOCK_KEY=<BOLD_SERVICES_UNLOCK_KEY>
      - BOLD_SERVICES_DB_TYPE=postgresql
      - BOLD_SERVICES_DB_HOST=pgdb
      - BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB=postgres
      - BOLD_SERVICES_DB_USER=postgres
      - BOLD_SERVICES_DB_PASSWORD=Admin@123
      - BOLD_SERVICES_USER_EMAIL=demo@boldbi.com
      - BOLD_SERVICES_USER_PASSWORD=Admin@123
    volumes:
      - boldservices_data:/application/app_data
    networks:
      - boldservices
    depends_on:
      - id-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  bi-web:
    container_name: bi_web_container
    image: gcr.io/boldbi-294612/boldbi-server:6.8.9
    restart: on-failure
    volumes: 
      - boldservices_data:/application/app_data
    networks:
      - boldservices
    depends_on:
      - id-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  bi-api:
    container_name: bi_api_container
    image: gcr.io/boldbi-294612/boldbi-server-api:6.8.9
    restart: on-failure
    volumes: 
      - boldservices_data:/application/app_data
    networks:
      - boldservices
    depends_on:
      - id-web
      - bi-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
      
  bi-jobs:
    container_name: bi_jobs_container
    image: gcr.io/boldbi-294612/boldbi-server-jobs:6.8.9
    restart: on-failure
    volumes: 
      - boldservices_data:/application/app_data
    networks:
      - boldservices
    depends_on:
      - id-web
      - bi-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
      
  bi-dataservice:
    container_name: bi_dataservice_container
    image: gcr.io/boldbi-294612/boldbi-designer:6.8.9
    restart: on-failure
    # environment:                         ## Refer README.md for available environment variables.
    #   - widget_bing_map_enable=false
    #   - widget_bing_map_api_key=""
    #   - AppSettings__locale-path=""
    volumes:
      - boldservices_data:/application/app_data
    networks:
      - boldservices
    depends_on:
      - id-web
      - bi-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  reverse-proxy:
    container_name: nginx
    image: nginx
    restart: on-failure
    volumes:
      -  "<default_conf_path>:/etc/nginx/conf.d/default.conf"
      # - "<ssl_cert_file_path>:/etc/ssl/domain.crt"
      # - "<ssl_key_file_path>:/etc/ssl/domain.key"
    ports:
      - "8085:80"
      # - "443:443"
    environment:
      - NGINX_PORT=80
    networks:
      - boldservices
    depends_on:
      - id-web
      - id-api
      - id-ums
      - bi-web
      - bi-api
      - bi-jobs
      - bi-dataservice
  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Admin@123
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - boldservices

networks:
  boldservices:
  
volumes:
  boldservices_data:
  db_data:

