version: '3.5'

services:
  id-web:
    container_name: id_web_container
    image: gcr.io/boldbi-294612/bold-identity:4.2.69
    restart: on-failure
    # environment:
      # - APP_BASE_URL= <app_base_url>
      # - INSTALL_OPTIONAL_LIBS= phantomjs,mongodb,mysql,influxdb,snowflake,oracle,npgsql
    volumes: 
      - boldbi_data:/application/app_data
    networks:
      - boldbi
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  id-api:
    container_name: id_api_container
    image: gcr.io/boldbi-294612/bold-identity-api:4.2.69
    restart: on-failure
    volumes: 
      - boldbi_data:/application/app_data
    networks:
      - boldbi
    depends_on:
      - id-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  id-ums:
    container_name: id_ums_container
    image: gcr.io/boldbi-294612/bold-ums:4.2.69
    restart: on-failure
    volumes: 
      - boldbi_data:/application/app_data
    networks:
      - boldbi
    depends_on:
      - id-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  bi-web:
    container_name: bi_web_container
    image: gcr.io/boldbi-294612/boldbi-server:4.2.69
    restart: on-failure
    volumes: 
      - boldbi_data:/application/app_data
    networks:
      - boldbi
    depends_on:
      - id-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  bi-api:
    container_name: bi_api_container
    image: gcr.io/boldbi-294612/boldbi-server-api:4.2.69
    restart: on-failure
    volumes: 
      - boldbi_data:/application/app_data
    networks:
      - boldbi
    depends_on:
      - id-web
      - bi-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
      
  bi-jobs:
    container_name: bi_jobs_container
    image: gcr.io/boldbi-294612/boldbi-server-jobs:4.2.69
    restart: on-failure
    volumes: 
      - boldbi_data:/application/app_data
    networks:
      - boldbi
    depends_on:
      - id-web
      - bi-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
      
  bi-dataservice:
    container_name: bi_dataservice_container
    image: gcr.io/boldbi-294612/boldbi-designer:4.2.69
    restart: on-failure
    environment:
      - widget_bing_map_enable=""
      - widget_bing_map_api_key=""
    volumes: 
      - boldbi_data:/application/app_data
    networks:
      - boldbi
    depends_on:
      - id-web
      - bi-web
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health-check"]
        interval: 10s
        timeout: 10s
        retries: 5
        
  reverse-proxy:
    container_name: nginx
    image: nginx
    restart: on-failure
    volumes:
      -  "D:/Devop/boldbi-docker-main/boldbi-docker-main/deploy/default.conf:/etc/nginx/conf.d/default.conf"
      # - "<ssl_cert_file_path>:/etc/ssl/domain.crt"
      # - "<ssl_key_file_path>:/etc/ssl/domain.key"
    ports:
      - "8085:80"
      # - "443:443"
    environment:
      - NGINX_PORT=80
    networks:
      - boldbi
    depends_on:
      - id-web
      - id-api
      - id-ums
      - bi-web
      - bi-api
      - bi-jobs
      - bi-dataservice
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: <Password>
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - boldbi

networks:
  boldbi:
  
volumes:
  boldbi_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '<host_path>'
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '<host_path>'